home/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('', views.home, name= 'home'),
    path('training/', views.training, name= 'training'),
    path('register/', views.registerform, name= 'register'),
    path('login/', views.loginform, name= 'account'),
    path('logout/', views.logoutfunc, name= 'logout'),
    path('update/', views.userupdate, name= 'update'),
    path('profile/', views.profile, name= 'profile'),
    path('upchange/', views.userpasswordchange, name= 'upchange'),
    path('enquires/', views.enquires, name= 'enquires'),
    path('allproduct/', views.allproduct, name= 'allproduct'),
    path('pendraw/', views.pendraw, name= 'pendraw'),
    path('giftbox/', views.giftbox, name= 'giftbox'),
    path('greetcard/', views.greetcard, name= 'greetcard'),
    path('picframe/', views.picframe, name= 'picframe'),
    path('searchbar/', views.searchbar, name= 'searchbar'),
    path('prod_det/<str:id>', views.prod_det, name= 'prod_det'),


    path('reset_password/', auth_views.PasswordResetView.as_view(template_name = 'accounts/password_reset.html'), name = 'reset_password'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name = 'accounts/password_reset_sent.html'), name = 'password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name = 'accounts/password_reset_guide.html'), name = 'password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name = 'accounts/password_reset_done.html'), name = 'password_reset_complete'),
]

order/urls.py
from django.urls import path
from . import views


app_name = 'order'

urlpatterns = [
    path('cart/', views.cart, name= 'cart'),
    path('addtoshopcart/', views.addtoshopcart, name='addtoshopcart'),
    path('updatequantity/', views.updatequantity, name='updatequantity'),
    path('checkout/', views.checkout, name='checkout'),
    path('placeorder/', views.placeorder, name='placeorder'),
    path('deletecourse/', views.deletecourse, name='deletecourse'),
    path('single_purchase/', views.single_purchase, name='single_purchase'),
    path('ordercompleted/<str:order_code>', views.ordercompleted, name='ordercompleted'),
    path('deletefromcart/<str:id>', views.deletefromcart, name='deletefromcart'),
]

home/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Home (models.Model):
    first_img = models.ImageField(upload_to = 'images/')
    pencil_drawing = models.ImageField(upload_to = 'images/')
    picture_framing = models.ImageField(upload_to = 'images/')
    gift_box = models.ImageField(upload_to = 'images/')
    greeting_card = models.ImageField(upload_to = 'images/')
    training = models.ImageField(upload_to = 'images/')
    appears = models.ImageField(upload_to = 'images/')
    review1 = models.ImageField(upload_to = 'images/')
    review2 = models.ImageField(upload_to = 'images/')
    review3 = models.ImageField(upload_to = 'images/')
    review4 = models.ImageField(upload_to = 'images/')

class Training (models.Model):
    beginners = models.ImageField(upload_to = 'images/')
    intermediate = models.ImageField(upload_to = 'images/')
    advanced = models.ImageField(upload_to = 'images/')
    t_video = models.FileField(upload_to = 'files/')
    carousel = models.ImageField(upload_to = 'images/', blank=True, null=True)

class Carousel(models.Model):
    carousel = models.ImageField(upload_to = 'images/')

class Enquires(models.Model):
    receiver = models.ForeignKey(User, on_delete=models.CASCADE)
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='clientenquiry')
    question = models.TextField(max_length=1000)
    date_added = models.DateTimeField(auto_now_add=True)
    time_added = models.TimeField(auto_now_add = True, null=True, blank=True)
    answered = models.BooleanField(default=False)

    def __str__(self):
        return '%s - %s' % (self.receiver, self.sender)

class Products (models.Model):
    CATEGORY = (
        ('Pencil Drawings', 'Pencil Drawings'),
        ('Picture Framing', 'Picture Framing'),
        ('Gift Boxes', 'Gift Boxes'),
        ('Greeting Cards', 'Greeting Cards'),
        ('Display', 'Display'),
    )
    category = models.CharField(choices=CATEGORY,  max_length=30)
    img= models.ImageField(upload_to = 'images/') 
    description = models.CharField(max_length=200, default='giftbox') 
    
class Prices (models.Model):
    CATEGORY = (
        ('Pencil Drawings', 'Pencil Drawings'),
        ('Picture Framing', 'Picture Framing'),
        ('Gift Boxes', 'Gift Boxes'),
        ('Greeting Cards', 'Greeting Cards'),
        ('Training', 'Training'),
    )
    category = models.CharField(choices=CATEGORY,  max_length=30)
    price1 = models.FloatField(blank=True, null=True)
    price2 = models.FloatField(blank=True, null=True)
    price3 = models.FloatField(blank=True, null=True)
    price4 = models.FloatField(blank=True, null=True)
    price5 = models.FloatField(blank=True, null=True)
    price6 = models.FloatField(blank=True, null=True)

home/forms.py
from django import forms
from django.forms import ModelForm, fields, widgets
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Enquires

class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length=30, help_text='username')
    first_name = forms.CharField(max_length=50, help_text='first_name')
    last_name = forms.CharField(max_length=50, help_text='last_name')

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'username', 'password1', 'password2')

def save(self, commit=True):
    user = super(RegisterForm, self).save(commit = False)
    user.email = self.cleaned_data['email']
    if commit:
        user.save()
    return user

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'username')

class EnquiresForm (forms.ModelForm):
    class Meta:
        model = Enquires
        fields = ('receiver', 'sender', 'question')

home/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.utils import timezone
from datetime import datetime, timedelta
from django.db.models import Max
import random
from .forms import *

from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash

from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from .models import *
from order.models import *

# Create your views here.
def home(request):
    home_img = Home.objects.get(pk=1)

    context = {
        'home_img': home_img, 
    }

    return render (request, 'home.html', context)

def training(request):
    training = Training.objects.get(pk=1)
    carousel = Carousel.objects.all()
    prices = Prices.objects.get(category='Training')

    context = {
        'training': training,
        'carousel': carousel,
        'prices': prices,
    }

    return render (request, 'my_training.html', context)

def registerform(request):
    form = RegisterForm(request.POST)
    if request.method == 'POST':

        if form.is_valid():
            user = form.save()

            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            is_staff = True
            user = authenticate(username = username, password=password)
            login(request, user)

            return redirect ('allproduct')
            # products

        else:
            messages.warning(request, form.errors)
            return redirect('account')

    context = {
        'form': form,
    }

    return render(request, 'account.html', context)

def loginform (request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username = username, password= password)
        if user:
            login(request,user)
            return redirect('allproduct')
        else:
            messages.info(request, 'Invalid username/password')

    return render(request, 'account.html')

@login_required(login_url='/login')
def logoutfunc(request):
    logout(request)
    return redirect('home')

@login_required(login_url='/login')
def profile (request):
    client = User.objects.get(username=request.user.username)
    order = ShopCart.objects.filter(order_placed= True, user=request.user)
    # .exclude(status= 'Completed')

    context = {
        'client': client,
        'order': order,
    }

    return render(request, 'profile.html', context)

@login_required(login_url='/login')
def userupdate (request):
    if request.method == 'POST':
        profileform = ProfileUpdateForm(request.POST, request.FILES, instance=request.user)
        if profileform.is_valid():

            profileform.save()
            messages.success(request, 'Your Account has been updated.')
            return redirect('profile')
        else:
            messages.warning(request, profileform.errors)
            return redirect('profile')
    return render (request, 'profile.html')

@login_required(login_url='/login')
def userpasswordchange(request):
    form = PasswordChangeForm(request.user, request.POST)

    if request.method == 'POST':
        form = PasswordChangeForm(user = request.user, data = request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            messages.success(request, 'Your password was successsfully updated')
            return redirect('profile')

        else:
            messages.warning(request, form.errors)
            return redirect ('upchange')

    context = {
        'form': form,
    }
    return render (request, 'userpasswordchange.html', context)

# messages - info, success, warning, error

@login_required(login_url='/login')
def enquires (request):
    user = request.user
    ask = User.objects.get(username = 'askme@admin')
    max_id = Enquires.objects.all().aggregate(max_id = Max("id"))['max_id']
    products = Enquires.objects.all().order_by('id')
    random_product = random.sample(list(products), int(max_id))
    # time_threshold = datetime.now() - timedelta(hours=24)
    # enquires = Enquires.objects.filter(
    #         date_added__range= [
    #         timezone.US(), timezone.now()
    #         ]
    # )
    # enquires = Enquires.objects.filter(date_added= time_threshold)

    now = datetime.now()

    time_threshold = now - timedelta(hours=24)
    # enquires = Enquires.objects.filter(
    #     date_added__range = (time_threshold,now)
    # )
    enquires = Enquires.objects.all()
    adminconvo = Enquires.objects.filter(sender__id=ask.id, receiver= user.id).filter(
        date_added__range = (time_threshold,now)
    )
    userconvo = Enquires.objects.filter(sender__id=user.id, receiver=ask.id).filter(
        date_added__range = (time_threshold,now)
    )
    form = EnquiresForm(request.POST)
    url = request.META.get('HTTP_REFERER')
    if request.method == 'POST':

        if form.is_valid():
            form.save()
            return redirect ('enquires')
        else:
            messages.warning(request, form.errors)
            return redirect ('enquires')

    context = {
        'form': form,
        'ask': ask,
        'enquires': enquires,
        'adminconvo': adminconvo,
        'userconvo': userconvo,
        'random_product': random_product,
    }

    # print(userconvo)
    return render (request, 'make_enquires.html', context)

# def random():
#     max_id = Enquires.objects.all().aggregate(max_id = Max("id"))['max_id']
#     while True:
#         pk = random.randint(1, max_id)
#         product = Enquires.objects.filter(pk=pk).first()
#         if product:
#             return product

# max_id = Products.objects.last().id
# random_id = random.randint(0, max_id)
# random_obj = Products.objects.filter(pk=random_id)

# random.choices(list)

def allproduct (request):
    max_id = Products.objects.exclude(category='Display').aggregate(max_id = Max("id"))['max_id']
    products = Products.objects.exclude(category='Display').order_by('id')
    random_product = random.sample(list(products), int(max_id)-2)

    prices = Products.objects.filter(category='Display')

    context = {
        'allproducts': random_product,
        'prices': prices,
    }

    return render (request, 'products.html', context)

def pendraw (request):
    penprod = Products.objects.filter(category='Pencil Drawings')

    context= {
        'penprod': penprod,
    }

    return render (request, 'pencil_drawing.html', context)

def giftbox (request):
    giftbox = Products.objects.filter(category='Gift Boxes')

    context= {
        'giftbox': giftbox,
    }

    return render (request, 'gift_boxes.html', context)

def greetcard (request):
    greetcard = Products.objects.filter(category='Greeting Cards')

    context= {
        'greetcard': greetcard,
    }

    return render (request, 'greeting_cards.html', context)

def picframe (request):
    picframe = Products.objects.filter(category='Picture Framing')

    context= {
        'picframe': picframe,
    }

    return render (request, 'picture_frames.html', context)

def searchbar (request):
    if request.method == 'GET':
        search = request.GET.get('search')
        pagesearch = Products.objects.filter(description__icontains= search).exclude(category='Display')
        picframe = Products.objects.filter(category='Picture Framing').filter(description__icontains= search)
        giftbox = Products.objects.filter(category='Gift Boxes').filter(description__icontains= search)
        greetcard = Products.objects.filter(category='Greeting Cards').filter(description__icontains= search)
        penprod = Products.objects.filter(category='Pencil Drawings').filter(description__icontains= search)

        context= {
            'search': search,
            'pagesearch': pagesearch,
            'picframe': picframe,
            'giftbox': giftbox,
            'greetcard': greetcard,
            'penprod': penprod,
        }

        return render (request, 'searchbar.html', context)

def prod_det (request, id):
    prod = Products.objects.get(pk = id)

    # max_id = Products.objects.filter(category = prod.category).exclude(id = prod.id).aggregate(max_id = Max("id"))['max_id']
    # products = Products.objects.filter(category = prod.category).exclude(id = prod.id).order_by('id')
    # more = random.sample(list(products), int(max_id))
    more = Products.objects.filter(category = prod.category).exclude(id = prod.id)

    picframe = Products.objects.filter(category='Picture Framing')
    giftbox = Products.objects.filter(category='Gift Boxes').exclude(description__icontains = 'Memory')
    membox = Products.objects.filter(category='Gift Boxes').filter(description__icontains = 'Memory')
    greetcard = Products.objects.filter(category='Greeting Cards')
    penprod = Products.objects.filter(category='Pencil Drawings')

    price = Prices.objects.get(category= prod.category)
    p = Prices.objects.get(category='Greeting Cards')
    price_avg = (p.price1 + p.price2)/2

    context = {
        'prod': prod,
        'price_avg':price_avg,
        'more': more,
        'picframe': picframe,
        'giftbox': giftbox,
        'membox': membox,
        'greetcard': greetcard,
        'penprod': penprod,
        'price': price,
    }

    return render (request, 'prod_det.html', context)

home/templates/account.html
{% extends 'base.html' %}
{% load static %}
{% block keywords %} 
order details, account
{% endblock keywords %}
{% block title %} Account {% endblock %}
{% block content %}

<style>
    .services .write {
        height: 28rem;
    }
</style>
{% if user.id is None %}
    <div>
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-success alert-{{message.tags}}" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    {{message}}
                </div>
            {% endfor %}
        {% endif %}
    </div>
    <div class="container-fluid secondblock account">
        <div class="row justify-content-center">
            <div class="col-lg-6 col-12 ">
                <div class="services" data-aos="flip-left">
                    <form action="{% url 'account' %}" method="POST">
                        {% csrf_token %}
                        <div class="write forgot">
                            <h4 class="purple">
                                Login
                            </h4>
                            <div class="forminputs">
                                Email Address: <br>
                                <input type="email" name="username" id=""> <br>
                                Password: <br>
                                <input type="password" name="password" id=""> <br>
                            </div>
                        </div>
                        <button class="learnmore white subbut">
                            Login
                        </button>
                        <a href="{% url 'reset_password' %}" class="purple">Forgot Password?</a>
                    </form>
                </div>
            </div>
            <div class="col-lg-6 col-12 ">
                <div class="services" data-aos="flip-left">
                    <form action="{% url 'register' %}"  method="POST">
                        {% csrf_token %}
                        <div class="write">
                            <h4 class="purple">
                                Register
                            </h4>
                            <div class="forminputs">
                                Email Address: <br>
                                <input type="email" name="username" id="field"> <br>
                                <!-- Email Address: <br> -->
                                <input type="hidden" name="email" id="result">
                                First Name: <br>
                                <input type="text" name="first_name" id=""> <br>
                                Last Name: <br>
                                <input type="text" name="last_name" id=""> <br>
                                Password: <br>
                                <input type="password" name="password1" id=""> <br>
                                Confirm Password: <br>
                                <input type="password" name="password2" id=""> <br>
                            </div>
                        </div>
                        <button class="learnmore white subbut">
                            Register
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endif %}

{% endblock %}

home/templates/base.html
<!DOCTYPE html>
{% load static %}
{% load humanize %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous"> 
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"> 
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css'>            
    <meta name="keywords" content="{% block keywords %} {% endblock keywords %}"> 

    
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static '' %}css/tenaj.css">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'media/favicon-96x96.png' %}">    
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
    <div class="container">
        <div class="row header">
            <span onclick="menu()" id="menu" class="material-icons col-2">
                menu
            </span>
            <div class="col-2 col-md-3 ">
                <a href="{% url 'home' %}">
                    <img src="{% static 'media/t_logo.jpeg' %}" alt="">
                </a>
            </div>
            <div class="col-lg-9 col-12 array">
                <ul>
                    <li><a href="{% url 'home' %}">Home</a></li>
                    <li><a href="{% url 'training' %}">My Training</a></li>
                    <li id="drop"><a href="{% url 'allproduct' %}">Products
                        <!-- <i class="nav-arrow fa fa-angle-down" aria-hidden="true" role="img"></i> -->
                        </a>
                        <!-- <div class="down">
                            <ul>
                                <li><a href="">Pencil Drawings</a></li>
                                <li><a href="">Gift Boxes</a></li>
                                <li><a href="">Greeting Cards</a></li>
                            </ul>
                        </div> -->
                    </li>
                    <li><a href="{% url 'enquires' %}">Make Enquires</a></li>
                    <li><a href="{% url 'order:cart' %}">Cart
                        <!-- <span class="material-icons">
                            shopping_cart
                        </span> -->
                    </a></li>
                    {% if user.id is None %}
                    <li><a href="{% url 'account' %}">Account</a></li>
                    {% endif %}
                    {% if user.id is not None %}
                    <li><a href="{% url 'profile' %}">{{ user.username }}'s Profile</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>

    {% block content %} {% endblock %}

    <div class="container footer">
        {% block endnote %} {% endblock %}
        <div class="row justify-content-center">
            <div class="col-lg-4 col-sm-6 col-12">
                <h6 class="orange">
                    SOCIAL MEDIA PAGES
                </h6>
                <a href="https://www.instagram.com/tenaj_art_craft">
                    <i class='fa fa-instagram'></i>
                </a>
                <a href="https://twitter.com/TenajArtCraft">
                    <i class='fa fa-twitter'></i>
                </a>
                <a href="https://youtube.com/channel/UCWgVDmQz0xn_E9nm3igc92w">
                    <i class='fa fa-youtube-play'></i>
                </a>
            </div>
            <div class="col-lg-4 col-sm-6 col-12">
                <h6 class="purple">
                    ADDRESS
                </h6>
                <address>
                    Tombia Area, Yenagoa, Bayelsa State
                </address>
                <a href="https://goo.gl/maps/5fHv4NdhQwvRbhFn9">
                    <i class='fa fa-map-marker'></i>                
                </a>          
            </div>
            <div class="col-lg-4 col-sm-6 col-12">
                <h6 class="orange">
                    CONTACT US
                </h6>
                <a href="https://wa.me/+2348165573297">
                    <i class='fa fa-whatsapp'></i>
                </a> 
                <!-- +2348165573297  <br> -->
                <a href="https://www.facebook.com/adeoye.oluwajuwonlojanet">
                    <i class="fa fa-facebook"></i>
                </a>
                <a href="https://telegram.me/Tenaj_Art_Craft">
                    <i class='fa fa-telegram'></i>
                </a>
                <a href="tel:+2348165573297">
                    <i class='fa fa-phone'></i>
                </a>
                <!-- +2348165573297 <br> -->
                <a href="mailto:tenajcreativeart@gmail.com">
                    <i class='fa fa-envelope'></i>
                </a>
                <!-- tenajcreativeart@gmail.com <br> -->
                <a href="https://www.linkedin.com/in/oluwajuwonlo-adeoye-009328162">
                    <i class="fa fa-linkedin"></i>
                </a>
                <!-- oluwajuwonlo-adeoye-009328162 -->
            </div>
        </div>
    </div>
    

    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
    <script>
        AOS.init();
    </script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script>
        document.getElementById("field").value =
        document.getElementById("result").value
    </script>
    <script type="text/javascript">
        $("#field").keyup(function(){
            update();
        })

        function update() {
            $("#result").val($('#field').val());
        }
    </script>

    <script>
        const size = document.getElementById('size');
        const price = document.getElementById('price');
        const size1 = document.getElementById('size1');
        const price1 = document.getElementById('price1');
        const size2 = document.getElementById('size2');
        const price2 = document.getElementById('price2');
        const size3 = document.getElementById('size3');
        const price3 = document.getElementById('price3');
        const size4 = document.getElementById('size4');
        const price4 = document.getElementById('price4');

        size.addEventListener('change', () => {
            if(size.checked === true) {
                price.checked = true;
            }
        })
        size1.addEventListener('change', () => {
            if(size1.checked === true) {
                price1.checked = true;
            }
        })
        size2.addEventListener('change', () => {
            if(size2.checked === true) {
                price2.checked = true;
            }
        })
        size3.addEventListener('change', () => {
            if(size3.checked === true) {
                price3.checked = true;
            }
        })
        size4.addEventListener('change', () => {
            if(size4.checked === true) {
                price4.checked = true;
            }
        })
    </script>

    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
    <script src="{% static 'js/tenaj.js' %}"></script>
</body>
</html>

home/templates/gift_boxes.html
{% extends 'base.html' %}

{% block keywords %} gift boxes {% endblock %}
{% block title %} Gift Boxes {% endblock %}
{% block content %}

    <div class="container-fluid products-header">
        <div class="row">
            <div class="col-lg-7 col-12 productlist">
                <ul>
                    <li><a href="{% url 'allproduct' %}">All products</a></li>
                    <li><a href="{% url 'pendraw' %}">Pencil Drawings</a></li>
                    <li><a href="{% url 'picframe' %}">Picture Framing</a></li>
                    <li><a style="text-decoration: 2px solid white underline;" href="{% url 'giftbox' %}">Gift Boxes</a></li>
                    <li><a href="{% url 'greetcard' %}">Greeting Cards</a></li>
                </ul>
            </div>
            {% block productsearch %} {% include 'product_search.html' %} {% endblock %}
        </div>
    </div>

    <div class="container products-first">
        <h1>
            <span class="purple">Gift</span>
            <span class="orange">Boxes</span>
        </h1>
    </div>

    <div class="container-fluid secondblock">
        <div class="row allproducts">
            {% for item in giftbox %}
            <div class="col-lg-2 col-md-3 col-sm-4 col-6 ">
                <div class="services">
                    <div class="write">
                        <img src="{{ item.img.url }}" alt="">
                        <h6 class="purple">
                            {{ item.category }}
                        </h6>
                    </div>
                    <div class="learnmore">
                        <a class="white" href="{% url 'prod_det' item.id %}">View</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>


    {% endblock %}

    {% block endnote %}
    <p>
        <b>MONEY BACK GUARANTEE, ORDER NOW </b>
    </p>
    {% endblock %}

home/templates/greeting_cards.html
{% extends 'base.html' %}

{% block keywords %} greeting cards {% endblock %}
{% block title %} Greeting Cards {% endblock %}
{% block content %}

    <div class="container-fluid products-header">
        <div class="row">
            <div class="col-lg-7 col-12 productlist">
                <ul>
                    <li><a href="{% url 'allproduct' %}">All products</a></li>
                    <li><a href="{% url 'pendraw' %}">Pencil Drawings</a></li>
                    <li><a href="{% url 'picframe' %}">Picture Framing</a></li>
                    <li><a href="{% url 'giftbox' %}">Gift Boxes</a></li>
                    <li><a style="text-decoration: 2px solid white underline;" href="{% url 'greetcard' %}">Greeting Cards</a></li>
                </ul>
            </div>
            {% block productsearch %} {% include 'product_search.html' %} {% endblock %}
        </div>
    </div>

    <div class="container products-first">
        <h1>
            <span class="purple">Greeting</span>
            <span class="orange">Cards</span>
        </h1>
    </div>

    <div class="container-fluid secondblock">
        <div class="row allproducts">
            {% for item in greetcard %}
            <div class="col-lg-2 col-md-3 col-sm-4 col-6 ">
                <div class="services">
                    <div class="write">
                        <img src="{{ item.img.url }}" alt="">
                        <h6 class="purple">
                            {{ item.category }}
                        </h6>
                    </div>
                    <div class="learnmore">
                        <a class="white" href="{% url 'prod_det' item.id %}">View</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>


    {% endblock %}

    {% block endnote %}
    <p>
        <b>MONEY BACK GUARANTEE, ORDER NOW </b>
    </p>
    {% endblock %}

home/templates/product_search.html
<div class="col-lg-5 col-12 productsearch">
    <form action="{% url 'searchbar' %}" method="GET">
        <input type="text" name="search" id="" placeholder="Memory Box">
        <button class="white" type="submit">
            <i class='fa fa-search white'></i> <b>Search</b>
        </button>
    </form>
</div>