home/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('', views.home, name= 'home'),
    path('training/', views.training, name= 'training'),
    path('register/', views.registerform, name= 'register'),
    path('login/', views.loginform, name= 'account'),
    path('logout/', views.logoutfunc, name= 'logout'),
    path('update/', views.userupdate, name= 'update'),
    path('profile/', views.profile, name= 'profile'),
    path('upchange/', views.userpasswordchange, name= 'upchange'),
    path('enquires/', views.enquires, name= 'enquires'),
    path('allproduct/', views.allproduct, name= 'allproduct'),
    path('pendraw/', views.pendraw, name= 'pendraw'),
    path('giftbox/', views.giftbox, name= 'giftbox'),
    path('greetcard/', views.greetcard, name= 'greetcard'),
    path('picframe/', views.picframe, name= 'picframe'),
    path('searchbar/', views.searchbar, name= 'searchbar'),
    path('prod_det/<str:id>', views.prod_det, name= 'prod_det'),


    path('reset_password/', auth_views.PasswordResetView.as_view(template_name = 'accounts/password_reset.html'), name = 'reset_password'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name = 'accounts/password_reset_sent.html'), name = 'password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name = 'accounts/password_reset_guide.html'), name = 'password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name = 'accounts/password_reset_done.html'), name = 'password_reset_complete'),
]

order/urls.py
from django.urls import path
from . import views


app_name = 'order'

urlpatterns = [
    path('cart/', views.cart, name= 'cart'),
    path('addtoshopcart/', views.addtoshopcart, name='addtoshopcart'),
    path('updatequantity/', views.updatequantity, name='updatequantity'),
    path('checkout/', views.checkout, name='checkout'),
    path('placeorder/', views.placeorder, name='placeorder'),
    path('deletecourse/', views.deletecourse, name='deletecourse'),
    path('single_purchase/', views.single_purchase, name='single_purchase'),
    path('ordercompleted/<str:order_code>', views.ordercompleted, name='ordercompleted'),
    path('deletefromcart/<str:id>', views.deletefromcart, name='deletefromcart'),
]

order/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.forms import UsernameField
from home.models import Products
from django.utils.safestring import mark_safe
# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(User, blank=True, null=True, on_delete=models.CASCADE)
    phone = models.CharField(blank=True, max_length=15)
    address = models.CharField(blank=True, max_length=15)
    city = models.CharField(blank=True, max_length=15)
    state = models.CharField(blank=True, max_length=15)
    country = models.CharField(blank=True, max_length=15)
    zipcode = models.CharField(blank=True, max_length=15)
    image = models.ImageField(blank=True, null=True, upload_to='images/users/', default='defaultpic.jpg')

    def __str__(self):
        return self.user.username

    
    @property
    def username(self):
        if self.user_id is not None:
            return self.user.first_name+ ' ' + self.user.last_name + '[' + self.user.username + ']'


    @property
    def email(self):
        if self.user_id is not None:
            return (self.user.email)

    def image_tag(self):
        return mark_safe('<img scr="{}" height="50"/>'.format(self.image.url))

    image_tag.short_description = 'Image'

    class Meta:
        db_table = 'userprofile'
        managed = True
        verbose_name = 'UserProfile'
        verbose_name_plural = 'UserProfiles'

class ShopCart (models.Model):
    user = models.ForeignKey(User, on_delete = models.SET_NULL, null=True)
    product = models.ForeignKey(Products, on_delete = models.SET_NULL, null=True, blank=True)
    quantity = models.IntegerField()
    price = models.FloatField()
    size = models.CharField(max_length=20)
    order_code = models.CharField(max_length=70, editable=False)
    order_placed = models.BooleanField(default=False)
    specification = models.TextField(max_length=1000, null=True, blank=True)

    def __str__(self):
        return self.product.category

    @property
    def amount(self):
        return self.price * self.quantity

class TrainingPurchase (models.Model):
    user = models.ForeignKey(User, on_delete = models.SET_NULL, null=True)
    price = models.FloatField()
    course = models.CharField(max_length=20)
    order_code = models.CharField(max_length=70, editable=False)
    order_placed = models.BooleanField(default=False)

class Order(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Preparing', 'Preparing'),
        ('OnShipping', 'OnShipping'),
        ('Completed', 'Completed'),
        ('Canceled', 'Canceled'),
    )
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    total = models.FloatField(null=True, blank=True)
    order_placed = models.BooleanField(default=False)
    order_code = models.CharField(max_length=70, editable=False)
    payment_code = models.CharField(max_length=8, editable=False)
    first_name = models.CharField(max_length=15)
    last_name = models.CharField(max_length=15)
    phone = models.CharField(blank=True, max_length=20)
    address = models.CharField(max_length=150, blank=True)
    city = models.CharField(blank=True, max_length=20)
    state = models.CharField (blank=True, null=True, max_length=20)
    country = models.CharField(blank=True, max_length=20)
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    adminnote = models.CharField(blank=True, max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    # def __str__(self):
    #     return self.user.username
        # return self.user.UsernameField

order/forms.py
from django.db.models import fields
from django.forms import ModelForm
from .models import*

class ShopCartForm(ModelForm):
    class Meta:
        model = ShopCart
        fields = ['quantity', 'size', 'price', 'specification']

class TrainingPurchaseForm(ModelForm):
    class Meta:
        model = ShopCart
        fields = ['course','price',]

class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'address', 'phone', 'city', 'state']

order/views.py
from django.shortcuts import render, redirect
import uuid

from django.contrib import messages
from .models import *
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
# from users.models import UserProfile
import json
import requests
import random
import string
import uuid
from django.views.decorators.http import require_POST
# Create your views here.

@require_POST
@login_required(login_url='/login')
def addtoshopcart(request):
    url = request.META.get('HTTP_REFERER')
    thequantity = int(request.POST['quantity'])
    thesize = request.POST.get('size', None)
    theprodid = request.POST['prodid']
    theprice = request.POST.get('price', None)
    specification = request.POST.get('specification', None)
    aprod = Products.objects.get(pk=theprodid)

    cart = ShopCart.objects.filter(order_placed=False).filter(user__username = request.user.username)

    if cart:
        prodchecker = ShopCart.objects.filter(product_id = aprod.id, size=thesize, quantity = thequantity, user__username = request.user.username, specification=specification).first()

        if prodchecker: #product exists in the cart, increment it
            prodchecker.quantity += thequantity
            prodchecker.size = thesize
            prodchecker.save()
            messages.success(request, "Product added to Shopcart")
            return redirect(url)

        else: # product is not in the cart, add it
            if theprice is not None:
                anitem = ShopCart()
                anitem.product=aprod
                anitem.user=request.user
                anitem.order_code=cart[0].order_code
                anitem.quantity=thequantity
                anitem.specification=specification
                anitem.size=thesize
                anitem.price=theprice
                anitem.order_placed=False
                anitem.save()
                messages.success(request, "Product added to Shopcart")
            else: messages.warning(request, 'Please pick a size')


    else: #create a new cart, generate order code
        if theprice is not None:
            ordercode = str(uuid.uuid4())
            newcart = ShopCart()
            newcart.product=aprod
            newcart.user=request.user
            newcart.order_code=ordercode
            newcart.quantity=thequantity
            newcart.specification=specification
            newcart.size=thesize
            newcart.price=theprice        
            newcart.order_placed=False
            newcart.save()
            messages.success(request, "Product added to Shopcart")
        else: messages.warning(request, 'Please pick a size')


    return redirect(url)

def cart (request):
    prodchecker = ShopCart.objects.filter(user__username = request.user.username, order_placed= False)
    subtotal=0
    vat = 0
    total= 0

    for item in prodchecker:
        subtotal += item.price * item.quantity

    vat = 0.075 * subtotal
    total = subtotal + vat

    context = {
        'prodchecker': prodchecker,
        'vat': vat,
        'total': total,
    }

    return render (request, 'cart.html', context)


@require_POST
@login_required(login_url='/login')
def updatequantity(request):
    url= request.META.get('HTTP_REFERER')
    newquantity = request.POST['itemquantity']
    theitem = ShopCart.objects.get(id=request.POST['itemid'])
    theitem.quantity = newquantity
    theitem.save()

    messages.success(request, "Product Quantity successsfully updated")
    return redirect(url)

@login_required(login_url='/login')
def deletefromcart(request,id):
    ShopCart.objects.filter(id=id).delete()
    messages.success(request, 'Item deleted from Shopcart.')
    return redirect('order:cart')

@login_required(login_url='/login')
def checkout (request):
    pendraw = Products.objects.filter(category= 'Pencil Drawings')
    picframe = Products.objects.filter(category= 'Picture Framing')
    prodchecker = ShopCart.objects.filter(user__username = request.user.username, order_placed= False)
    client = User.objects.get(username=request.user.username)
    client2 = Order.objects.filter(user=request.user).first()
    subtotal=0
    vat = 0
    total= 0

    for item in prodchecker:
        if item.product.category == 'Picture Framing' or item.product.category == 'Pencil Drawings':
            subtotal += item.price * item.quantity

    vat = 0.075 * subtotal
    total = subtotal + vat

    context = {
        'prodchecker': prodchecker,
        'vat': vat,
        'total': total,
        'pendraw': pendraw,
        'client': client,
        'client2': client2,
        'picframe': picframe,
    }

    return render (request, 'check_out.html', context)

@require_POST
@login_required(login_url='/login')
def placeorder(request):
    api_key = 'sk_live_b8c0ebd1db821c213d0ac1d65752ef44a2e39448'
    url = 'https://api.paystack.co/transaction/initialize'
    ordercode =  request.POST['order_number']
    callback_url = 'http://127.0.0.1:8000/order/ordercompleted/code'
    autogen_ref = ''.join(random.choices(string.digits + string.ascii_letters, k=8))
    current_user = User.objects.get(username = request.user.username)
    user = UserProfile.objects.get(user_id = current_user.id)
    total = float(request.POST['amount']) * 100    
    

    headers = {'Authorization': f'Bearer {api_key}'}
    data = {'reference': autogen_ref, 'amount':int(total), 'order_number':ordercode, 'email':user.email, 'callback_url':callback_url }

    
    # making a request to PAYSTACK 
    try:
        r = requests.post(url, headers=headers, json=data)
    except Exception:
        messages.error(request, 'Network busy. Please try again in few minutes. Thank You!')
    else:
        # create an order 
        transback = json.loads(r.text)
        
        rd_url = transback['data']['authorization_url']
        theuser= UserProfile.objects.filter(user=request.user).first()
        order = Order()
        order.user=theuser.user
        order.first_name=theuser.user.first_name
        order.last_name=theuser.user.last_name
        order.phone=theuser.phone
        order.city=theuser.city
        order.state=theuser.state
        order.order_code= ordercode
        order.payment_code = autogen_ref
        order.total=total
        order.order_placed = True
        order.save()

        profile= UserProfile.objects.get(user__username = request.user.username)
        shopcart= ShopCart.objects.filter(order_placed=False).filter(user__username= request.user.username)
        cart = TrainingPurchase.objects.filter(order_placed=False).filter(user__username = request.user.username)

        #cleaning the shopcart
        for item in shopcart:
            if item.product.category == 'Picture Framing' or item.product.category == 'Pencil Drawings':
                item.order_placed= True
                item.save()

        for item in cart:
            item.order_placed= True
            item.save()
        return redirect(rd_url)
    return redirect('order:checkout')

@login_required(login_url='/login')
def single_purchase(request):
    thecourse = request.POST.get('course', None)
    total = request.POST.get('price', None)
    client = User.objects.get(username=request.user.username)
    client2 = Order.objects.filter(user=request.user).first()

    cart = TrainingPurchase.objects.filter(order_placed=False).filter(user__username = request.user.username,)

    if cart:
        messages.warning(request, 'A course already in cart')

    else:
        ordercode = str(uuid.uuid4())
        anitem = TrainingPurchase()
        anitem.user=request.user
        anitem.order_code=ordercode
        anitem.course=thecourse
        anitem.price=total
        anitem.order_placed=False
        anitem.save()

    context = {
        'thecourse': thecourse,
        'total': total,
        'client': client,
        'client2': client2,
    }

    return render (request, 'training_purchase.html', context)

@login_required(login_url='/login')
def deletecourse(request):
    TrainingPurchase.objects.get(user= request.user, order_placed=False).delete()
    # messages.success(request, 'Item deleted from Shopcart.')
    return redirect('training')

@login_required(login_url='/login')
def ordercompleted(request, order_code):
    profile= UserProfile.objects.get(user__username = request.user.username)
    shopcart= ShopCart.objects.filter(order_placed=False).filter(user__username= request.user.username)
    cart = TrainingPurchase.objects.filter(order_placed=False).filter(user__username = request.user.username,)

    #cleaning the shopcart
    # for item in shopcart:
    #     item.order_placed= True
    #     item.save()

        #reducing quantity instock
        # aproduct = Product.objects.get(id=item.product.id)
        # aproduct.quantity_instock = item.quantity
        # aproduct.save()

    # for item in cart:
    #     item.order_placed= True
    #     item.save()


    context = {
        'shopcart': shopcart,
        'profile': profile
    }
    return render (request, 'ordercompleted.html', context)

order/templates/cart.html
{% extends 'base.html' %}
{% load humanize %}

{% block keywords %} cart, order {% endblock %}
{% block title %} Cart {% endblock %}
{% block content %}

{% if not prodchecker %}
    <div class="container-fluid secondblock cart">
        <div class="row justify-content-center">
            <div class="col-lg-11 col-12 ">
                <div class="services" data-aos="flip-left">
                    <div class="emptycart">
                        <span class="material-icons purple">
                            shopping_cart
                        </span>
                        <p>
                            <b>No item in cart yet</b> <br>
                            Your lover deserves a token of love as gifts
                        </p>
                        <div class="learnmore">
                            <a class="white" href="{% url 'allproduct' %}">Start Shopping</a>
                        </div>
                    </div>
                </div>
            </div>           
        </div>
    </div>
{% else %}
    <div class="container-fluid cart secondblock">
        <div>
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-success alert-{{message.tags}}" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        {{message}}
                    </div>
                {% endfor %}
            {% endif %}
        </div>
        <div class="row justify-content-center">
            <div class="col-lg-8 col-12 ">
                <div class="services" data-aos="flip-left">
                    <div class="write">
                        <h4 class="purple">
                            Cart({{ prodchecker.count }})
                        </h4>
                        <table>
                            <tr class="products-header">
                                <th class="white">Item Specifications</th>
                                <th class="white">Amount <br> ( <i class='fa-solid fa-naira-sign'></i> )</th>
                            </tr>
                            {% for item in prodchecker %}
                            <tr>
                                <td>
                                    <img src="{{ item.product.img.url }}" alt="">
                                    <div>
                                        <p><b>{{ item.product.category }}</b></p>
                                        Size: <b>{{ item.size }}</b>
                                        <!-- <select name="size" id="">
                                            <option value="">8 by 10 </option>
                                            <option value="">12 by 16 </option>
                                            <option value="">16 by 20 </option>
                                            <option value="">20 by 24 </option>
                                            <option value="">24 by 36 </option>
                                        </select>  -->
                                        <br>
                                        <form action="{% url 'order:updatequantity' %}" method="post">
                                        {% csrf_token %}
                                            Quantity:<input type="number" name="itemquantity" id="" value="{{ item.quantity }}" min="1"> <br> <br>
                                            <button style="padding: 0;" class="learnmore white subbut">Update</button>
                                            <input type="hidden" name="itemid" value="{{ item.id }}">
                                        </form>
                                        <a class="red" href="{% url 'order:deletefromcart' item.id %}"><b>remove</b></a>
                                    </div>
                                </td>
                                <td>
                                    <p>
                                        {{ item.amount|floatformat:0|intcomma }}
                                    </p>
                                </td>
                            </tr>
                            {% endfor %}
                        </table> <br>
                        <div class="learnmore white">
                            vat <i style="font-size:small" class='fa-solid fa-naira-sign'>{{ vat|floatformat:0|intcomma }}</i> <br>
                            <tr>
                                <td>Total</td>
                                <td><i class='fa-solid fa-naira-sign'>{{ total|floatformat:0|intcomma }}</i></td>
                            </tr>
                        </div>
                    </div>
                    <div class="orderbut">
                        <div class="learnmore">
                            <a class="white" href="{% url 'allproduct' %}">Shop More</a>
                        </div>
                        <div class="learnmore">
                            <a class="white" href="{% url 'order:checkout' %}">Check Out</a>
                        </div>
                    </div>
                </div>
            </div>           
        </div>
    </div> 

{% endif %}

{% endblock %}

{% block endnote %}
{% endblock %}

order/templates/check_out.html
{% extends 'base.html' %}
{% load humanize %}

{% block keywords %} cart, order {% endblock %}
{% block title %} Cart {% endblock %}
{% block content %}

<style>
    @media (max-width: 767px) {
    
        .account td:first-child{
            width: 80%;
        }
        
        .account td:nth-child(2){
            width: 20%;
        }
    }
</style>

    <div class="container-fluid secondblock account checkout">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-success alert-{{message.tags}}" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    {{message}}
                </div>
            {% endfor %}
        {% endif %}
        <div class="row justify-content-center">
            <div class="col-lg-6 col-12 ">
                <div class="services" data-aos="flip-left">
                    <form action="">
                        <div class="write">
                            <h4 class="purple">
                                Order Summary
                            </h4>
                            <table>
                                <tr class="products-header">
                                    <th class="white">Item</th>
                                    <th class="white">Quantity</th>
                                    <th class="white">Size</th>
                                    <th class="white">Amount</th>
                                </tr>
                                {% for item in prodchecker %}
                                {% if item.product.category == 'Picture Framing' or item.product.category == 'Pencil Drawings' %}
                                <tr>
                                    <td>{{ item.product.category }}</td>
                                    <td>{{ item.quantity }}</td>
                                    <td>{{ item.size }}</td>
                                    <td><i class='fa-solid fa-naira-sign'></i>{{ item.amount|floatformat:0|intcomma }}</td>
                                </tr>
                                {% endif %}
                                {% endfor %}
                            </table>
                            <div class="learnmore white">
                                vat <i style="font-size:small" class='fa-solid fa-naira-sign'>{{ vat|floatformat:0|intcomma }}</i> <br>
                                <tr>
                                    <td>Total</td>
                                <td><i class='fa-solid fa-naira-sign'>{{ total|floatformat:0|intcomma }}</i></td>
                                </tr>
                            </div>
                        </div><br>
                        <p>
                            Only items under the categories 'Pencil Drawings'
                            and 'Picture Framing' can be preordered. <br>
                            Other items will be ordered after necessary communications
                            via email have been made.
                        </p>
                    </form>
                </div>
            </div>
            <div class="col-lg-6 col-12 ">
                <div class="checkservice services" data-aos="flip-left">
                    <form action="{% url 'order:placeorder' %}" method="POST">
                    {% csrf_token %}
                        <div class="write">
                            <h4 class="purple">
                                Order Details
                            </h4>
                            <div class="forminputs">
                                First Name: <br>
                                <input type="text" name="first_name" value="{{ client.first_name }}" id=""> <br>
                                Last Name: <br>
                                <input type="text" name="last_name" value="{{ client.last_name }}" id=""> <br>
                                Phone Number: <br>
                                <input type="number" name="phone" value="{{ client2.phone }}" id=""> <br>
                                Address: <br>
                                <input type="text" name="address" value="{{ client2.address }}" id=""> <br>
                                City: <br>
                                <input type="text" name="city" value="{{ client2.city }}" id=""> <br>
                                State: <br>
                                <input type="text" name="state" value="{{ client2.state }}" id=""> <br>
                                <input type="hidden" name="amount" value="{{total}}">
                                <input type="hidden" name="order_number" value="{{order_code}}">
                            </div>
                        </div>
                        <button class="learnmore white subbut">
                            Proceed to Order
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    {% endblock %}
    
    {% block endnote %}
    {% endblock %}

order/templates/ordercompleted.html
{% extends 'base.html' %}
{% load humanize %}

{% block keywords %} cart, order {% endblock %}
{% block title %} Cart {% endblock %}
{% block content %}

    <div class="container-fluid secondblock cart">
        <div class="row justify-content-center">
            <div class="col-lg-9 col-12 ">
                <div class="services" data-aos="flip-left">
                    <div class="emptycart">
                        <h4>Dear <span class="purple">{{profile.user.first_name}} {{profile.user.last_name}},</span></h4>
                        <h5>Your Order is Completed</h5>
                        <p>Thank You for your patronage</p>
                        <div class="learnmore">
                            <a class="white" href="{% url 'allproduct' %}">Shop More</a>
                        </div>
                    </div>
                </div>
            </div>           
        </div>
    </div>

{% endblock %}

{% block endnote %}
{% endblock %}

order/templates/training_purchase.html
{% extends 'base.html' %}
{% load humanize %}

{% block keywords %} cart, order {% endblock %}
{% block title %} Cart {% endblock %}
{% block content %}

<style>
    @media (max-width: 767px) {
    
        .account td:first-child{
            width: 70%;
        }
        
        .account td:nth-child(2){
            width: 30%;
        }
    }
</style>

    <div class="container-fluid secondblock account checkout">
        <div>
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-success alert-{{message.tags}}" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        {{message}}
                    </div>
                {% endfor %}
            {% endif %}
        </div>
        <div class="row justify-content-center">
            <div class="col-lg-6 col-12 ">
                <div class="services" data-aos="flip-left">
                    <form action="">
                        <div class="write">
                            <h4 class="purple">
                                Course Purchase
                            </h4>
                            <table>
                                <tr class="products-header">
                                    <th class="white">Course</th>
                                    <th class="white">Amount</th>
                                </tr>
                                <tr>
                                    <td>{{ thecourse }}</td>
                                    <td><i class='fa-solid fa-naira-sign'></i>{{ total | floatformat:0 | intcomma }}</td>
                                </tr>
                            </table>
                            <a class="red" href="{% url 'order:deletecourse' %}"><b>remove</b></a>
                        </div>
                        <p>
                            Please we will need you to fill out the 
                            following form to buy the course. <br>
                            Once filled up, we will communicate with you
                            through the email provided.
                        </p>
                    </form>
                </div>
            </div>
            
            <div class="col-lg-6 col-12 ">
                <div class="checkservice services" data-aos="flip-left">
                    <form action="{% url 'order:placeorder' %}" method="POST">
                        {% csrf_token %}
                        <div class="write">
                            <h4 class="purple">
                                Please fill this form
                            </h4>
                            <div class="forminputs">
                                First Name: <br>
                                <input type="text" name="first_name" value="{{ client.first_name }}" id=""> <br>
                                Last Name: <br>
                                <input type="text" name="last_name" value="{{ client.last_name }}" id=""> <br>
                                Phone Number: <br>
                                <input type="number" name="phone" value="{{ client2.phone }}" id=""> <br>
                                Address: <br>
                                <input type="text" name="address" value="{{ client2.address }}" id=""> <br>
                                City: <br>
                                <input type="text" name="city" value="{{ client2.city }}" id=""> <br>
                                State: <br>
                                <input type="text" name="state" value="{{ client2.state }}" id=""> <br>
                                <input type="hidden" name="amount" value="{{total}}">
                                <input type="hidden" name="order_number" value="{{order_code}}">
                            </div>
                        </div>
                        <button class="learnmore white subbut">
                            Proceed to Order
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>


    {% endblock %}
    
    {% block endnote %}
    {% endblock %}